// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/7/2024, 7:51:45 AM
const configMerger = require("C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/plugins/**/*.{js,ts,mjs}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/composables/**/*.{js,ts,mjs}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/utils/**/*.{js,ts,mjs}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/Documents/VisualStudio/Uru/protocolos/SMTP-Frontend/app.config.{js,ts,mjs}"] } }));

module.exports = config
